#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python tools/relation_train_net.py \
    --config-file 'configs/decor_vg_predcls.yaml' \
    MODEL.ROI_RELATION_HEAD.USE_GT_BOX True \
    MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True \
    MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS True \
    MODEL.ROI_RELATION_HEAD.PREDICTOR PrototypeEmbeddingNetwork \
    DTYPE float32 \
    SOLVER.IMS_PER_BATCH 8 \
    TEST.IMS_PER_BATCH 1 \
    SOLVER.MAX_ITER 20000 \
    SOLVER.BASE_LR 1e-3 \
    SOLVER.SCHEDULE.TYPE WarmupMultiStepLR \
    MODEL.ROI_RELATION_HEAD.BATCH_SIZE_PER_IMAGE 512 \
    SOLVER.STEPS '(28000,48000)' \
    SOLVER.VAL_PERIOD 5000 \
    SOLVER.CHECKPOINT_PERIOD 5000 \
    SOLVER.PRE_VAL False \
    SOLVER.GRAD_NORM_CLIP 5.0 \
    OUTPUT_DIR checkpoints/predcls-0.5 \
    INPUT.MIN_SIZE_TRAIN '(600,)' \
    INPUT.MAX_SIZE_TRAIN 1000 \
    INPUT.MIN_SIZE_TEST 600 \
    INPUT.MAX_SIZE_TEST 1000 \
    DATALOADER.NUM_WORKERS 4
